Updated file

diff --git a/dumpdatabase b/dumpdatabase
--- a/dumpdatabase
+++ b/dumpdatabase
@@ -28,13 +28,43 @@ backupnow () {
 	printf "*** ${db}\n"
 	printf "Exporting ${db} database(s) to /${localDir}/${ThisFile}..."
 	if [ "${db}" = "all" ]; then
-		{ mysqldump -uroot --all-databases | gzip -c > /${localDir}/${ThisFile}; } >/dev/null 2>&1 && \
+		{ mariadb-dump -uroot --all-databases | gzip -c > /${localDir}/${ThisFile}; } >/dev/null 2>&1 && \
 			printf "Done.\n" || \
 			{ printf " Errors.\n"
 				terrors=$((terrors+1))
 				printf "\n${db} DB Backup with errors.\n\n"; }
+		echo "Making /var/lib/mysql tarbal..."
+		systemctl stop mariadb
+		# Check the exit status of the systemctl command
+		if [ $? -eq 0 ]; then
+			# Verify if MariaDB is actually running
+			if systemctl is-active mariadb | grep -q "inactive"; then
+				echo "MariaDB stopped successfully"
+			else
+				echo "MariaDB failed to stop or is running"
+				# Optionally, check the error log for details
+				# cat /var/log/mariadb/mariadb.log 2>/dev/null || echo "Error log not found"
+			fi
+		else
+			echo "Failed to execute systemctl stop mariadb"
+		fi
+		tar -czf /${localDir}/mariadb-dir.tgz /var/lib/mysql
+		systemctl start mariadb
+		# Check the exit status of the systemctl command
+		if [ $? -eq 0 ]; then
+			# Verify if MariaDB is actually running
+			if systemctl is-active mariadb | grep -q "active"; then
+				echo "MariaDB started successfully"
+			else
+				echo "MariaDB failed to start or is not running"
+				# Optionally, check the error log for details
+				# cat /var/log/mariadb/mariadb.log 2>/dev/null || echo "Error log not found"
+			fi
+		else
+			echo "Failed to execute systemctl start mariadb"
+		fi
 	else
-		{ mysqldump -uroot --databases ${db} | gzip -c > /${localDir}/${ThisFile}; } >/dev/null 2>&1 && \
+		{ mariadb-dump -uroot --databases ${db} | gzip -c > /${localDir}/${ThisFile}; } >/dev/null 2>&1 && \
 			printf "Done.\n" || \
 			{ printf " Errors.\n"
 				terrors=$((terrors+1))
